### ISSUE TITLE
[Bug]: Can't make it work on some city

### ISSUE THREAD

**Issue by Mara-Li** [Alexis06030631/meteofrance_api#1]
The city I was trying was "Villefranche-sur-Mer" and I get "unknow id". Code used:
```js
const {getWeather} = require('meteofrance_api')
const {getPlace} = require('meteofrance_api')

const villefranche = await getPlace('Villefranche-sur-Mer'); 
console.log(villefranche)
const meteo = await getWeather(villefranche[0].id); //id = 61590
console.log(meteo) 
```

Log:
```
The request was malformed
Message: Unknown ID
```

**Comment by Alexis06030631** [comment]
Sorry for the late reply and thank you for reporting the error.

After checking the problem, it seems that the new version of the MeteoFrance api no longer supports city IDs.

To solve this problem, I've updated the extension. It is therefore imperative to update the extension for the following code to work: (Current version V.1.2.1)
```console
npm i meteofrance_api@latest 
```
Using your code as an example, here are the 2 methods for obtaining the results:
```javascript
const {getWeather} = require('meteofrance_api')
const {getPlace} = require('meteofrance_api')

const villefranche = await getPlace('Villefranche-sur-Mer'); 
const meteo = await getWeather(villefranche[0]);
console.log(meteo)
```
or
```javascript
const {getWeather} = require('meteofrance_api')
const {getPlace} = require('meteofrance_api')

const villefranche = await getPlace('Villefranche-sur-Mer'); 
const meteo = await villefranche[0].getWeather();
console.log(meteo)
```

PS: Documentation has been updated. Go to the doc to see how it works
Don't hesitate to contact me again if you have a new problem!
